import { StyleSheet } from 'react-native';
import colors from '../../shared/tokens/colors';

export const postCreateStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.white },
  content: { padding: 16, paddingBottom: 24 },
  label: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
    marginTop: 16,
    marginBottom: 8,
  },
  catRow: { flexDirection: 'row', gap: 8 },
  cat: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: colors.surface,
  },
  catActive: { backgroundColor: colors.primary },
  catText: { fontSize: 13, fontWeight: '700', color: colors.textSub },
  catTextActive: { color: '#fff' },
  titleInput: {
    marginTop: 16,
    height: 48,
    borderRadius: 12,
    paddingHorizontal: 14,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.border,
    fontSize: 15,
    color: colors.textPrimary,
  },
  bodyInput: {
    marginTop: 12,
    minHeight: 140,
    borderRadius: 12,
    padding: 14,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.border,
    fontSize: 15,
    color: colors.textPrimary,
  },
  locRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.surfaceAlt,
  },
  locText: {
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: '600',
    flex: 1,
  },
  changeBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: colors.primary,
  },
  changeText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  starRow: { flexDirection: 'row', gap: 6 },
  star: { fontSize: 30, color: '#f5b301' },
  dayTabsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  addDay: { fontSize: 13, color: colors.primary, fontWeight: '700' },
  dayTabs: { flexDirection: 'row', gap: 8, marginTop: 8, marginBottom: 8 },
  dayTab: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: colors.surface,
  },
  dayTabActive: { backgroundColor: colors.primary },
  dayTabText: { fontSize: 13, fontWeight: '700', color: colors.textSub },
  dayTabTextActive: { color: '#fff' },
  routeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
  },
  routeNum: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  routeNumText: { color: '#fff', fontSize: 12, fontWeight: '800' },
  routeName: { fontSize: 14, fontWeight: '700', color: colors.textPrimary },
  routeSub: { fontSize: 12, color: colors.textMuted },
  addItemRow: { flexDirection: 'row', gap: 8, marginTop: 8 },
  addItemInput: {
    flex: 1,
    height: 42,
    borderRadius: 10,
    paddingHorizontal: 12,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.border,
    fontSize: 14,
    color: colors.textPrimary,
  },
  addItemBtn: {
    paddingHorizontal: 16,
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: colors.tint,
  },
  addItemBtnText: { color: colors.primary, fontSize: 13, fontWeight: '700' },
  addPhoto: {
    width: 80,
    height: 80,
    borderRadius: 12,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  addPhotoIcon: { fontSize: 20 },
  addPhotoText: { fontSize: 11, color: colors.textMuted, marginTop: 2 },
  thumbWrap: { marginRight: 8 },
  thumb: {
    width: 80,
    height: 80,
    borderRadius: 12,
    backgroundColor: colors.tintStrong,
  },
  thumbX: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  thumbXText: { color: '#fff', fontSize: 12 },
  footer: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  fBtn: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
  },
  primary: { backgroundColor: colors.primary },
  primaryText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  ghost: {
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  ghostText: { color: colors.textSub, fontSize: 16, fontWeight: '700' },
});
