import { StyleSheet } from 'react-native';
import colors from '../../shared/tokens/colors';

export const postDetailStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { padding: 16, paddingBottom: 24 },
  authorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.profileBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarIcon: { fontSize: 15 },
  author: { fontSize: 14, fontWeight: '700', color: colors.textPrimary },
  time: { fontSize: 12, color: colors.textMuted },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.textPrimary,
    lineHeight: 28,
    marginBottom: 12,
  },
  body: { fontSize: 15, lineHeight: 24, color: colors.text, marginBottom: 16 },
  metaRow: {
    flexDirection: 'row',
    gap: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  meta: { fontSize: 13, color: colors.textSub, fontWeight: '600' },
  commentsTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.textPrimary,
    marginTop: 16,
    marginBottom: 8,
  },
  comment: { paddingVertical: 10 },
  reply: { marginLeft: 38, marginTop: 4 },
  cHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  cAvatar: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.profileBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cAvatarIcon: { fontSize: 12 },
  cAuthor: { fontSize: 13, fontWeight: '700', color: colors.textPrimary },
  cTime: { fontSize: 11, color: colors.textMuted },
  cText: { fontSize: 14, lineHeight: 20, color: colors.text, marginLeft: 32 },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    backgroundColor: colors.white,
  },
  input: {
    flex: 1,
    height: 42,
    borderRadius: 21,
    paddingHorizontal: 16,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.border,
    fontSize: 14,
    color: colors.textPrimary,
  },
  submitBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 21,
    backgroundColor: colors.primary,
  },
  submitText: { color: '#fff', fontSize: 14, fontWeight: '700' },
});
