import { StyleSheet } from 'react-native';
import colors from '../../shared/tokens/colors';

export const travelPreferenceStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  header: {
    paddingHorizontal: 24,
    paddingTop: 4,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  back: {},
  title: { fontSize: 22, fontWeight: '700', color: colors.text },
  content: { paddingHorizontal: 24, paddingBottom: 120 },
  lead: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    color: colors.textSecondary,
  },
  section: {
    marginTop: 28,
    marginBottom: 12,
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
  },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  chip: {
    minHeight: 48,
    paddingHorizontal: 18,
    justifyContent: 'center',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  chipOn: { borderColor: colors.primaryFill, backgroundColor: colors.primaryFill },
  chipText: { fontSize: 16, color: colors.text },
  chipTextOn: { color: colors.textOnPrimary, fontWeight: '600' },
  stepper: { flexDirection: 'row', alignItems: 'center', gap: 20 },
  stepBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  count: { fontSize: 22, fontWeight: '700', color: colors.text },
  hint: { marginTop: 8, fontSize: 14, color: colors.textSecondary },
  loading: { marginTop: 40 },
  footer: {
    paddingHorizontal: 24,
    paddingTop: 12,
    backgroundColor: colors.background,
  },
  primaryBtn: {
    minHeight: 54,
    marginBottom: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryFill,
  },
  primaryBtnOff: { opacity: 0.5 },
  primaryText: { fontSize: 16, fontWeight: '600', color: colors.textOnPrimary },
});
