import { StyleSheet } from 'react-native';
import colors from '../../assets/constants/colors';

export const missionDetailStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { padding: 16 },
  map: {
    height: 150,
    borderRadius: 16,
    backgroundColor: colors.tintStrong,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  pin: { fontSize: 32 },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  desc: {
    fontSize: 14,
    lineHeight: 21,
    color: colors.textSub,
    marginBottom: 20,
  },
  verifyBox: {
    backgroundColor: colors.cardBg,
    borderRadius: 16,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: colors.border,
    paddingVertical: 28,
    alignItems: 'center',
    gap: 12,
  },
  camCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  camIcon: { fontSize: 26 },
  verifyBtn: {
    backgroundColor: colors.tint,
    borderRadius: 20,
    paddingHorizontal: 22,
    paddingVertical: 9,
  },
  verifyBtnText: { color: colors.primary, fontSize: 14, fontWeight: '700' },
  hint: { fontSize: 12, color: colors.textMuted },
  footer: { flexDirection: 'row', gap: 10, padding: 16 },
  fBtn: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
  },
  primary: { backgroundColor: colors.primary },
  primaryText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  ghost: {
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  ghostText: { color: colors.textSub, fontSize: 16, fontWeight: '700' },
});
