import { StyleSheet } from 'react-native';
import colors from '../../assets/constants/colors';

export const missionVerifyStyles = StyleSheet.create({
  cam: { flex: 1, backgroundColor: '#000' },
  camHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 48,
  },
  camBack: { color: '#fff', fontSize: 28 },
  camTitle: { color: '#fff', fontSize: 16, fontWeight: '700' },
  grid: { flex: 1 },
  v: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  h: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  camBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 36,
    paddingVertical: 20,
  },
  thumb: { width: 40, height: 40, borderRadius: 8, backgroundColor: '#444' },
  shutter: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 4,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shutterIn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#fff',
  },
  flip: { color: '#fff', fontSize: 26, width: 40, textAlign: 'center' },
  center: {
    flex: 1,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  logo: {
    fontSize: 30,
    fontWeight: '900',
    fontStyle: 'italic',
    marginBottom: 24,
  },
  lp: { color: colors.primary },
  lt: { color: colors.primaryDark },
  bubble: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 12,
    marginBottom: 16,
  },
  bubbleText: {
    fontSize: 14,
    color: colors.noteText,
    textAlign: 'center',
    lineHeight: 20,
  },
  cat: { fontSize: 88, marginBottom: 12 },
  doneTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  doneDesc: { fontSize: 14, color: colors.textSub, marginBottom: 32 },
  doneBtns: { alignSelf: 'stretch', gap: 12 },
  dBtn: { borderRadius: 14, paddingVertical: 16, alignItems: 'center' },
  dPrimary: { backgroundColor: colors.primary },
  dPrimaryText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  dGhost: { backgroundColor: colors.tint },
  dGhostText: { color: colors.primary, fontSize: 16, fontWeight: '700' },
});
