import { StyleSheet } from 'react-native';
import colors from '../../assets/constants/colors';

export const recordMapStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  map: { flex: 1, backgroundColor: colors.tintStrong },
  mapHint: {
    position: 'absolute',
    top: 16,
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  mapHintText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  marker: { position: 'absolute', alignItems: 'center' },
  markerPin: { fontSize: 28 },
  fabCol: { position: 'absolute', right: 16, gap: 10 },
  fab: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  fabIcon: { fontSize: 20, color: '#fff' },
  sheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    shadowColor: '#1a2a3a',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 8,
  },
  handle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    marginBottom: 12,
  },
  sheetTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 10,
  },
  routeCard: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8 },
  routeBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.tint,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginBottom: 6,
  },
  routeBadgeText: { color: colors.primary, fontSize: 11, fontWeight: '800' },
  routeThumb: {
    width: 64,
    height: 64,
    borderRadius: 10,
    backgroundColor: colors.tintStrong,
    marginRight: 12,
  },
  routeBody: { flex: 1 },
  routeTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 2,
  },
  routeDesc: { fontSize: 12, color: colors.textSub, marginBottom: 4 },
  routeMeta: { fontSize: 11, color: colors.textMuted },
});
