import { StyleSheet } from 'react-native';
import colors from '../../shared/tokens/colors';

// 피그마 E1 (402pt): 파란 헤더 268 · 본문 354 · 좌우 여백 24
export const profileStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  content: { paddingBottom: 32 },

  header: {
    backgroundColor: colors.primary,
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 52,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: { fontSize: 24, fontWeight: '700', color: colors.white },
  headerCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCircleIcon: { width: 18, height: 18, tintColor: colors.primary },

  profileRow: { marginTop: 24, flexDirection: 'row', alignItems: 'flex-start' },
  avatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: { width: '100%', height: '100%' },
  avatarInitial: { fontSize: 24, fontWeight: '700', color: colors.primary },
  profileInfo: { flex: 1, marginLeft: 16, paddingTop: 6 },
  nickname: { fontSize: 18, fontWeight: '600', color: colors.white },
  themeBadge: {
    alignSelf: 'flex-start',
    marginTop: 8,
    height: 26,
    paddingHorizontal: 12,
    borderRadius: 13,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  themeBadgeText: { fontSize: 11, fontWeight: '500', color: colors.white },
  handle: { marginTop: 10, fontSize: 12, color: colors.onPrimaryMuted },
  editBtn: {
    height: 34,
    paddingHorizontal: 16,
    borderRadius: 17,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editBtnText: { fontSize: 11, fontWeight: '500', color: colors.primary },

  // 통계 카드는 파란 헤더에 걸쳐 놓인다
  statsCard: {
    marginTop: -36,
    marginHorizontal: 24,
    height: 84,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    backgroundColor: colors.white,
  },
  statCol: { flex: 1, alignItems: 'center', gap: 6 },
  statValue: { fontSize: 18, fontWeight: '600', color: colors.text },
  statLabel: { fontSize: 11, fontWeight: '500', color: colors.textSecondary },
  statDivider: { width: 1, height: 40, backgroundColor: colors.border },

  section: { marginTop: 28, paddingHorizontal: 24 },
  sectionTitle: { fontSize: 18, fontWeight: '600', color: colors.text },

  mapCard: {
    marginTop: 8,
    borderRadius: 16,
    backgroundColor: colors.tint,
    padding: 20,
  },
  mapGrid: { flexDirection: 'row', gap: 10, justifyContent: 'center' },
  mapCell: {
    width: 46,
    height: 46,
    borderRadius: 10,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapCellFlag: { fontSize: 22 },
  mapFooter: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mapSummary: { flex: 1, fontSize: 12, color: colors.primaryDark },
  moreBtn: {
    height: 26,
    paddingHorizontal: 14,
    borderRadius: 13,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moreBtnText: { fontSize: 11, fontWeight: '500', color: colors.white },

  settingsRow: {
    marginTop: 8,
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: colors.white,
  },
  settingsRowText: { fontSize: 15, color: colors.text },
  settingsRowDanger: { color: colors.badge },
  settingsRowChevron: { fontSize: 15, fontWeight: '600', color: colors.textTertiary },
});
